require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssemblyToolsController do

  # This should return the minimal set of attributes required to create a valid
  # AssemblyTool. As you add validations to AssemblyTool, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssemblyToolsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all assembly_tools as @assembly_tools" do
      assembly_tool = AssemblyTool.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assembly_tools).should eq([assembly_tool])
    end
  end

  describe "GET show" do
    it "assigns the requested assembly_tool as @assembly_tool" do
      assembly_tool = AssemblyTool.create! valid_attributes
      get :show, {:id => assembly_tool.to_param}, valid_session
      assigns(:assembly_tool).should eq(assembly_tool)
    end
  end

  describe "GET new" do
    it "assigns a new assembly_tool as @assembly_tool" do
      get :new, {}, valid_session
      assigns(:assembly_tool).should be_a_new(AssemblyTool)
    end
  end

  describe "GET edit" do
    it "assigns the requested assembly_tool as @assembly_tool" do
      assembly_tool = AssemblyTool.create! valid_attributes
      get :edit, {:id => assembly_tool.to_param}, valid_session
      assigns(:assembly_tool).should eq(assembly_tool)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssemblyTool" do
        expect {
          post :create, {:assembly_tool => valid_attributes}, valid_session
        }.to change(AssemblyTool, :count).by(1)
      end

      it "assigns a newly created assembly_tool as @assembly_tool" do
        post :create, {:assembly_tool => valid_attributes}, valid_session
        assigns(:assembly_tool).should be_a(AssemblyTool)
        assigns(:assembly_tool).should be_persisted
      end

      it "redirects to the created assembly_tool" do
        post :create, {:assembly_tool => valid_attributes}, valid_session
        response.should redirect_to(AssemblyTool.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assembly_tool as @assembly_tool" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyTool.any_instance.stub(:save).and_return(false)
        post :create, {:assembly_tool => {}}, valid_session
        assigns(:assembly_tool).should be_a_new(AssemblyTool)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyTool.any_instance.stub(:save).and_return(false)
        post :create, {:assembly_tool => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assembly_tool" do
        assembly_tool = AssemblyTool.create! valid_attributes
        # Assuming there are no other assembly_tools in the database, this
        # specifies that the AssemblyTool created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssemblyTool.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => assembly_tool.to_param, :assembly_tool => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested assembly_tool as @assembly_tool" do
        assembly_tool = AssemblyTool.create! valid_attributes
        put :update, {:id => assembly_tool.to_param, :assembly_tool => valid_attributes}, valid_session
        assigns(:assembly_tool).should eq(assembly_tool)
      end

      it "redirects to the assembly_tool" do
        assembly_tool = AssemblyTool.create! valid_attributes
        put :update, {:id => assembly_tool.to_param, :assembly_tool => valid_attributes}, valid_session
        response.should redirect_to(assembly_tool)
      end
    end

    describe "with invalid params" do
      it "assigns the assembly_tool as @assembly_tool" do
        assembly_tool = AssemblyTool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyTool.any_instance.stub(:save).and_return(false)
        put :update, {:id => assembly_tool.to_param, :assembly_tool => {}}, valid_session
        assigns(:assembly_tool).should eq(assembly_tool)
      end

      it "re-renders the 'edit' template" do
        assembly_tool = AssemblyTool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssemblyTool.any_instance.stub(:save).and_return(false)
        put :update, {:id => assembly_tool.to_param, :assembly_tool => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assembly_tool" do
      assembly_tool = AssemblyTool.create! valid_attributes
      expect {
        delete :destroy, {:id => assembly_tool.to_param}, valid_session
      }.to change(AssemblyTool, :count).by(-1)
    end

    it "redirects to the assembly_tools list" do
      assembly_tool = AssemblyTool.create! valid_attributes
      delete :destroy, {:id => assembly_tool.to_param}, valid_session
      response.should redirect_to(assembly_tools_url)
    end
  end

end
