require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CombinationToolsController do

  # This should return the minimal set of attributes required to create a valid
  # CombinationTool. As you add validations to CombinationTool, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CombinationToolsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all combination_tools as @combination_tools" do
      combination_tool = CombinationTool.create! valid_attributes
      get :index, {}, valid_session
      assigns(:combination_tools).should eq([combination_tool])
    end
  end

  describe "GET show" do
    it "assigns the requested combination_tool as @combination_tool" do
      combination_tool = CombinationTool.create! valid_attributes
      get :show, {:id => combination_tool.to_param}, valid_session
      assigns(:combination_tool).should eq(combination_tool)
    end
  end

  describe "GET new" do
    it "assigns a new combination_tool as @combination_tool" do
      get :new, {}, valid_session
      assigns(:combination_tool).should be_a_new(CombinationTool)
    end
  end

  describe "GET edit" do
    it "assigns the requested combination_tool as @combination_tool" do
      combination_tool = CombinationTool.create! valid_attributes
      get :edit, {:id => combination_tool.to_param}, valid_session
      assigns(:combination_tool).should eq(combination_tool)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CombinationTool" do
        expect {
          post :create, {:combination_tool => valid_attributes}, valid_session
        }.to change(CombinationTool, :count).by(1)
      end

      it "assigns a newly created combination_tool as @combination_tool" do
        post :create, {:combination_tool => valid_attributes}, valid_session
        assigns(:combination_tool).should be_a(CombinationTool)
        assigns(:combination_tool).should be_persisted
      end

      it "redirects to the created combination_tool" do
        post :create, {:combination_tool => valid_attributes}, valid_session
        response.should redirect_to(CombinationTool.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved combination_tool as @combination_tool" do
        # Trigger the behavior that occurs when invalid params are submitted
        CombinationTool.any_instance.stub(:save).and_return(false)
        post :create, {:combination_tool => {}}, valid_session
        assigns(:combination_tool).should be_a_new(CombinationTool)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CombinationTool.any_instance.stub(:save).and_return(false)
        post :create, {:combination_tool => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested combination_tool" do
        combination_tool = CombinationTool.create! valid_attributes
        # Assuming there are no other combination_tools in the database, this
        # specifies that the CombinationTool created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CombinationTool.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => combination_tool.to_param, :combination_tool => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested combination_tool as @combination_tool" do
        combination_tool = CombinationTool.create! valid_attributes
        put :update, {:id => combination_tool.to_param, :combination_tool => valid_attributes}, valid_session
        assigns(:combination_tool).should eq(combination_tool)
      end

      it "redirects to the combination_tool" do
        combination_tool = CombinationTool.create! valid_attributes
        put :update, {:id => combination_tool.to_param, :combination_tool => valid_attributes}, valid_session
        response.should redirect_to(combination_tool)
      end
    end

    describe "with invalid params" do
      it "assigns the combination_tool as @combination_tool" do
        combination_tool = CombinationTool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CombinationTool.any_instance.stub(:save).and_return(false)
        put :update, {:id => combination_tool.to_param, :combination_tool => {}}, valid_session
        assigns(:combination_tool).should eq(combination_tool)
      end

      it "re-renders the 'edit' template" do
        combination_tool = CombinationTool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CombinationTool.any_instance.stub(:save).and_return(false)
        put :update, {:id => combination_tool.to_param, :combination_tool => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested combination_tool" do
      combination_tool = CombinationTool.create! valid_attributes
      expect {
        delete :destroy, {:id => combination_tool.to_param}, valid_session
      }.to change(CombinationTool, :count).by(-1)
    end

    it "redirects to the combination_tools list" do
      combination_tool = CombinationTool.create! valid_attributes
      delete :destroy, {:id => combination_tool.to_param}, valid_session
      response.should redirect_to(combination_tools_url)
    end
  end

end
