require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceStockOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # ServiceStockOrder. As you add validations to ServiceStockOrder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServiceStockOrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all service_stock_orders as @service_stock_orders" do
      service_stock_order = ServiceStockOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:service_stock_orders).should eq([service_stock_order])
    end
  end

  describe "GET show" do
    it "assigns the requested service_stock_order as @service_stock_order" do
      service_stock_order = ServiceStockOrder.create! valid_attributes
      get :show, {:id => service_stock_order.to_param}, valid_session
      assigns(:service_stock_order).should eq(service_stock_order)
    end
  end

  describe "GET new" do
    it "assigns a new service_stock_order as @service_stock_order" do
      get :new, {}, valid_session
      assigns(:service_stock_order).should be_a_new(ServiceStockOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_stock_order as @service_stock_order" do
      service_stock_order = ServiceStockOrder.create! valid_attributes
      get :edit, {:id => service_stock_order.to_param}, valid_session
      assigns(:service_stock_order).should eq(service_stock_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServiceStockOrder" do
        expect {
          post :create, {:service_stock_order => valid_attributes}, valid_session
        }.to change(ServiceStockOrder, :count).by(1)
      end

      it "assigns a newly created service_stock_order as @service_stock_order" do
        post :create, {:service_stock_order => valid_attributes}, valid_session
        assigns(:service_stock_order).should be_a(ServiceStockOrder)
        assigns(:service_stock_order).should be_persisted
      end

      it "redirects to the created service_stock_order" do
        post :create, {:service_stock_order => valid_attributes}, valid_session
        response.should redirect_to(ServiceStockOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_stock_order as @service_stock_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceStockOrder.any_instance.stub(:save).and_return(false)
        post :create, {:service_stock_order => {}}, valid_session
        assigns(:service_stock_order).should be_a_new(ServiceStockOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceStockOrder.any_instance.stub(:save).and_return(false)
        post :create, {:service_stock_order => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_stock_order" do
        service_stock_order = ServiceStockOrder.create! valid_attributes
        # Assuming there are no other service_stock_orders in the database, this
        # specifies that the ServiceStockOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServiceStockOrder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => service_stock_order.to_param, :service_stock_order => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested service_stock_order as @service_stock_order" do
        service_stock_order = ServiceStockOrder.create! valid_attributes
        put :update, {:id => service_stock_order.to_param, :service_stock_order => valid_attributes}, valid_session
        assigns(:service_stock_order).should eq(service_stock_order)
      end

      it "redirects to the service_stock_order" do
        service_stock_order = ServiceStockOrder.create! valid_attributes
        put :update, {:id => service_stock_order.to_param, :service_stock_order => valid_attributes}, valid_session
        response.should redirect_to(service_stock_order)
      end
    end

    describe "with invalid params" do
      it "assigns the service_stock_order as @service_stock_order" do
        service_stock_order = ServiceStockOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceStockOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_stock_order.to_param, :service_stock_order => {}}, valid_session
        assigns(:service_stock_order).should eq(service_stock_order)
      end

      it "re-renders the 'edit' template" do
        service_stock_order = ServiceStockOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceStockOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_stock_order.to_param, :service_stock_order => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_stock_order" do
      service_stock_order = ServiceStockOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => service_stock_order.to_param}, valid_session
      }.to change(ServiceStockOrder, :count).by(-1)
    end

    it "redirects to the service_stock_orders list" do
      service_stock_order = ServiceStockOrder.create! valid_attributes
      delete :destroy, {:id => service_stock_order.to_param}, valid_session
      response.should redirect_to(service_stock_orders_url)
    end
  end

end
