require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SettingDevicesController do

  # This should return the minimal set of attributes required to create a valid
  # SettingDevice. As you add validations to SettingDevice, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SettingDevicesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all setting_devices as @setting_devices" do
      setting_device = SettingDevice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:setting_devices).should eq([setting_device])
    end
  end

  describe "GET show" do
    it "assigns the requested setting_device as @setting_device" do
      setting_device = SettingDevice.create! valid_attributes
      get :show, {:id => setting_device.to_param}, valid_session
      assigns(:setting_device).should eq(setting_device)
    end
  end

  describe "GET new" do
    it "assigns a new setting_device as @setting_device" do
      get :new, {}, valid_session
      assigns(:setting_device).should be_a_new(SettingDevice)
    end
  end

  describe "GET edit" do
    it "assigns the requested setting_device as @setting_device" do
      setting_device = SettingDevice.create! valid_attributes
      get :edit, {:id => setting_device.to_param}, valid_session
      assigns(:setting_device).should eq(setting_device)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SettingDevice" do
        expect {
          post :create, {:setting_device => valid_attributes}, valid_session
        }.to change(SettingDevice, :count).by(1)
      end

      it "assigns a newly created setting_device as @setting_device" do
        post :create, {:setting_device => valid_attributes}, valid_session
        assigns(:setting_device).should be_a(SettingDevice)
        assigns(:setting_device).should be_persisted
      end

      it "redirects to the created setting_device" do
        post :create, {:setting_device => valid_attributes}, valid_session
        response.should redirect_to(SettingDevice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved setting_device as @setting_device" do
        # Trigger the behavior that occurs when invalid params are submitted
        SettingDevice.any_instance.stub(:save).and_return(false)
        post :create, {:setting_device => {}}, valid_session
        assigns(:setting_device).should be_a_new(SettingDevice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SettingDevice.any_instance.stub(:save).and_return(false)
        post :create, {:setting_device => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested setting_device" do
        setting_device = SettingDevice.create! valid_attributes
        # Assuming there are no other setting_devices in the database, this
        # specifies that the SettingDevice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SettingDevice.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => setting_device.to_param, :setting_device => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested setting_device as @setting_device" do
        setting_device = SettingDevice.create! valid_attributes
        put :update, {:id => setting_device.to_param, :setting_device => valid_attributes}, valid_session
        assigns(:setting_device).should eq(setting_device)
      end

      it "redirects to the setting_device" do
        setting_device = SettingDevice.create! valid_attributes
        put :update, {:id => setting_device.to_param, :setting_device => valid_attributes}, valid_session
        response.should redirect_to(setting_device)
      end
    end

    describe "with invalid params" do
      it "assigns the setting_device as @setting_device" do
        setting_device = SettingDevice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SettingDevice.any_instance.stub(:save).and_return(false)
        put :update, {:id => setting_device.to_param, :setting_device => {}}, valid_session
        assigns(:setting_device).should eq(setting_device)
      end

      it "re-renders the 'edit' template" do
        setting_device = SettingDevice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SettingDevice.any_instance.stub(:save).and_return(false)
        put :update, {:id => setting_device.to_param, :setting_device => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested setting_device" do
      setting_device = SettingDevice.create! valid_attributes
      expect {
        delete :destroy, {:id => setting_device.to_param}, valid_session
      }.to change(SettingDevice, :count).by(-1)
    end

    it "redirects to the setting_devices list" do
      setting_device = SettingDevice.create! valid_attributes
      delete :destroy, {:id => setting_device.to_param}, valid_session
      response.should redirect_to(setting_devices_url)
    end
  end

end
