require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ToolMaterialsController do

  # This should return the minimal set of attributes required to create a valid
  # ToolMaterial. As you add validations to ToolMaterial, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ToolMaterialsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tool_materials as @tool_materials" do
      tool_material = ToolMaterial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tool_materials).should eq([tool_material])
    end
  end

  describe "GET show" do
    it "assigns the requested tool_material as @tool_material" do
      tool_material = ToolMaterial.create! valid_attributes
      get :show, {:id => tool_material.to_param}, valid_session
      assigns(:tool_material).should eq(tool_material)
    end
  end

  describe "GET new" do
    it "assigns a new tool_material as @tool_material" do
      get :new, {}, valid_session
      assigns(:tool_material).should be_a_new(ToolMaterial)
    end
  end

  describe "GET edit" do
    it "assigns the requested tool_material as @tool_material" do
      tool_material = ToolMaterial.create! valid_attributes
      get :edit, {:id => tool_material.to_param}, valid_session
      assigns(:tool_material).should eq(tool_material)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ToolMaterial" do
        expect {
          post :create, {:tool_material => valid_attributes}, valid_session
        }.to change(ToolMaterial, :count).by(1)
      end

      it "assigns a newly created tool_material as @tool_material" do
        post :create, {:tool_material => valid_attributes}, valid_session
        assigns(:tool_material).should be_a(ToolMaterial)
        assigns(:tool_material).should be_persisted
      end

      it "redirects to the created tool_material" do
        post :create, {:tool_material => valid_attributes}, valid_session
        response.should redirect_to(ToolMaterial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tool_material as @tool_material" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToolMaterial.any_instance.stub(:save).and_return(false)
        post :create, {:tool_material => {}}, valid_session
        assigns(:tool_material).should be_a_new(ToolMaterial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ToolMaterial.any_instance.stub(:save).and_return(false)
        post :create, {:tool_material => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tool_material" do
        tool_material = ToolMaterial.create! valid_attributes
        # Assuming there are no other tool_materials in the database, this
        # specifies that the ToolMaterial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ToolMaterial.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tool_material.to_param, :tool_material => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tool_material as @tool_material" do
        tool_material = ToolMaterial.create! valid_attributes
        put :update, {:id => tool_material.to_param, :tool_material => valid_attributes}, valid_session
        assigns(:tool_material).should eq(tool_material)
      end

      it "redirects to the tool_material" do
        tool_material = ToolMaterial.create! valid_attributes
        put :update, {:id => tool_material.to_param, :tool_material => valid_attributes}, valid_session
        response.should redirect_to(tool_material)
      end
    end

    describe "with invalid params" do
      it "assigns the tool_material as @tool_material" do
        tool_material = ToolMaterial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToolMaterial.any_instance.stub(:save).and_return(false)
        put :update, {:id => tool_material.to_param, :tool_material => {}}, valid_session
        assigns(:tool_material).should eq(tool_material)
      end

      it "re-renders the 'edit' template" do
        tool_material = ToolMaterial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ToolMaterial.any_instance.stub(:save).and_return(false)
        put :update, {:id => tool_material.to_param, :tool_material => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tool_material" do
      tool_material = ToolMaterial.create! valid_attributes
      expect {
        delete :destroy, {:id => tool_material.to_param}, valid_session
      }.to change(ToolMaterial, :count).by(-1)
    end

    it "redirects to the tool_materials list" do
      tool_material = ToolMaterial.create! valid_attributes
      delete :destroy, {:id => tool_material.to_param}, valid_session
      response.should redirect_to(tool_materials_url)
    end
  end

end
