require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TunningWorkOrderSharpenItemsController do

  # This should return the minimal set of attributes required to create a valid
  # TunningWorkOrderSharpenItem. As you add validations to TunningWorkOrderSharpenItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TunningWorkOrderSharpenItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tunning_work_order_sharpen_items as @tunning_work_order_sharpen_items" do
      tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tunning_work_order_sharpen_items).should eq([tunning_work_order_sharpen_item])
    end
  end

  describe "GET show" do
    it "assigns the requested tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
      tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
      get :show, {:id => tunning_work_order_sharpen_item.to_param}, valid_session
      assigns(:tunning_work_order_sharpen_item).should eq(tunning_work_order_sharpen_item)
    end
  end

  describe "GET new" do
    it "assigns a new tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
      get :new, {}, valid_session
      assigns(:tunning_work_order_sharpen_item).should be_a_new(TunningWorkOrderSharpenItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
      tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
      get :edit, {:id => tunning_work_order_sharpen_item.to_param}, valid_session
      assigns(:tunning_work_order_sharpen_item).should eq(tunning_work_order_sharpen_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TunningWorkOrderSharpenItem" do
        expect {
          post :create, {:tunning_work_order_sharpen_item => valid_attributes}, valid_session
        }.to change(TunningWorkOrderSharpenItem, :count).by(1)
      end

      it "assigns a newly created tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
        post :create, {:tunning_work_order_sharpen_item => valid_attributes}, valid_session
        assigns(:tunning_work_order_sharpen_item).should be_a(TunningWorkOrderSharpenItem)
        assigns(:tunning_work_order_sharpen_item).should be_persisted
      end

      it "redirects to the created tunning_work_order_sharpen_item" do
        post :create, {:tunning_work_order_sharpen_item => valid_attributes}, valid_session
        response.should redirect_to(TunningWorkOrderSharpenItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        TunningWorkOrderSharpenItem.any_instance.stub(:save).and_return(false)
        post :create, {:tunning_work_order_sharpen_item => {}}, valid_session
        assigns(:tunning_work_order_sharpen_item).should be_a_new(TunningWorkOrderSharpenItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TunningWorkOrderSharpenItem.any_instance.stub(:save).and_return(false)
        post :create, {:tunning_work_order_sharpen_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tunning_work_order_sharpen_item" do
        tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
        # Assuming there are no other tunning_work_order_sharpen_items in the database, this
        # specifies that the TunningWorkOrderSharpenItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TunningWorkOrderSharpenItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tunning_work_order_sharpen_item.to_param, :tunning_work_order_sharpen_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
        tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
        put :update, {:id => tunning_work_order_sharpen_item.to_param, :tunning_work_order_sharpen_item => valid_attributes}, valid_session
        assigns(:tunning_work_order_sharpen_item).should eq(tunning_work_order_sharpen_item)
      end

      it "redirects to the tunning_work_order_sharpen_item" do
        tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
        put :update, {:id => tunning_work_order_sharpen_item.to_param, :tunning_work_order_sharpen_item => valid_attributes}, valid_session
        response.should redirect_to(tunning_work_order_sharpen_item)
      end
    end

    describe "with invalid params" do
      it "assigns the tunning_work_order_sharpen_item as @tunning_work_order_sharpen_item" do
        tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TunningWorkOrderSharpenItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => tunning_work_order_sharpen_item.to_param, :tunning_work_order_sharpen_item => {}}, valid_session
        assigns(:tunning_work_order_sharpen_item).should eq(tunning_work_order_sharpen_item)
      end

      it "re-renders the 'edit' template" do
        tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TunningWorkOrderSharpenItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => tunning_work_order_sharpen_item.to_param, :tunning_work_order_sharpen_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tunning_work_order_sharpen_item" do
      tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
      expect {
        delete :destroy, {:id => tunning_work_order_sharpen_item.to_param}, valid_session
      }.to change(TunningWorkOrderSharpenItem, :count).by(-1)
    end

    it "redirects to the tunning_work_order_sharpen_items list" do
      tunning_work_order_sharpen_item = TunningWorkOrderSharpenItem.create! valid_attributes
      delete :destroy, {:id => tunning_work_order_sharpen_item.to_param}, valid_session
      response.should redirect_to(tunning_work_order_sharpen_items_url)
    end
  end

end
